---
- name: Verificando um valor estranho
  hosts: all
  tasks:
  - name: Verificando no CentOS/OpenSUSE
    shell: 'echo {{ansible_distribution}} $USER'
    register: output
  - name: Inspecionando a variavel
    debug:
      msg: 'A saída foi {{output.stdout}}'
    #- name: Verificando no Debian
    #shell: 'echo {{ansible_distribution}}'
