- name: Provisionando um servidor Web
  hosts: minion
  become: yes
  tasks:
  - name: Instalação do pacote apache no servidor minion
    package:
      name: apache2 
      state: present
  - file:
      path: /var/www/html/infra-agil
      state: directory
  - unarchive:
      src: /root/playbooks/files/site.tar.gz
      dest: /var/www/html/infra-agil
  - service:
      name: apache2
      state: started      
      enabled: yes
